language: node_js
cache:
  npm: false
node_js:
  - "node"
  - "12"
  - "10"
  - "8"
addons:
  chrome: stable
matrix:
  allow_failures:
    - node_js: node
env:
  global:
    - KARMA_TEST_NODE_VERSION=12
