name: CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  node-ci:
    name: Node CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: ['10.x', '12.x', '14.x']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Run CI
      run: npm test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: './target/coverage/report/lcov.info'
  web-ci:
    name: Web CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      CI_RUN_KARMA: true
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install
      uses: ianwalter/puppeteer@v2.0.0
      with:
        args: npm install
    - name: Run CI
      uses: ianwalter/puppeteer@v2.0.0
      with:
        args: npm test
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: './target/coverage/report/lcov.info'
